# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '01-sql-server-basic'
    Contents: '**.tf'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# - task: ArchiveFiles@1
#   inputs:
#     rootFolder: '01-sql-server-basic'
#     includeRootFolder: true
#     archiveType: 'zip'
#     archiveFile: '$(Build.ArtifactStagingDirectory)/dm2-$(Build.BuildId).zip'
#     replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'


# steps:
# - task: ArchiveFiles@1
#   inputs:
#     rootFolder: 'sql-server-basic-2.0'
#     includeRootFolder: true
#     archiveType: 'zip'
#     archiveFile: '$(Build.ArtifactStagingDirectory)/dm2-$(Build.BuildId).zip'
#     replaceExistingArchive: true

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)/dm2-$(Build.BuildId).zip'
#     ArtifactName: 'dm2'
#     publishLocation: 'Container'